### ISSUE TITLE
Feature request: Add top to bottom flow direction

### ISSUE THREAD

**Issue by mydudechris** [abynim/UserFlows#3]
Would it be possible to add an option that allows users to specify the direction of the flow diagram? For example, I'm using this plugin with a desktop design and the long, left to right, flow of the PDF is a little awkward to share. It'd be awesome if I could tell the plugin to generate a top to bottom flow that coincided with the natural flow of a multipage PDF document.

**Comment by abynim** [comment]
@mydudechris Thanks for the suggestion! I've added this feature in a branch here: https://github.com/abynim/UserFlows/tree/flow-direction

Since it's not a common feature I've made it a setting for now. You can switch to `Vertical` flow direction in the Settings dialog and then try exporting your flows. 

Would you please test it and let me know if it works as expected? Will wait for you to confirm before merging it with the master branch.
